Repository InternLM/InternEvo, pull requests merged in 2024-02, with the labels that each got.

#15 feat(model): update modeling_internlm2 with configs
  .gitignore
  configs/_base_/default_runtime.py
  configs/_base_/models/internlm2_20B.py
  configs/_base_/models/internlm2_7B.py
  configs/_base_/models/internlm_20B.py
  configs/_base_/models/internlm_7B.py
  configs/demo.py
  internlm/model/__init__.py
  internlm/model/modeling_internlm2.py
  internlm/utils/utils.py
  train.py
Labels: enhancement

#45 feat(tests): update ci e2e tests
  .github/workflows/e2e_test.yaml
  .github/workflows/weekly_test.yaml
  configs/7B_sft.py
  internlm/utils/model_checkpoint.py
  tests/test_training/test_forward_output_no_fa.py
  tests/test_training/test_loss.py
Labels: Stale

#43 feat(code-docs): update doc tensor parallel
  doc/code-docs/locales/en/LC_MESSAGES/parallel.po
  doc/code-docs/source/parallel.rst
  doc/imgs/isp.png
  doc/imgs/msp.png
  doc/imgs/mtp.png
Labels: documentation

#55 feat(switch topology): add control switch
  internlm/initialize/launch.py
Labels: enhancement
